/*
 * Projeto destribuido por DEVKEWI COMPANY - Todos os direitos reservados.
 * Para alteração do código fonte estará disposto a concordar com termos.
 */
package me.kewi.interfaces;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import me.kewi.Excel;

/**
 *
 * @author Jane
 */
public class Editando extends javax.swing.JFrame {

    /**
     * Creates new form Editando
     */
    public Editando() {
        initComponents();
    }

    public JLabel getOS() {
        return jOS;
    }

    public JLabel getNome() {
        return jNome;
    }

    public JLabel getTelefone() {
        return jTelefone;
    }

    public JLabel getjDia() {
        return jDia;
    }

    public JLabel getjEstado() {
        return jEstado;
    }

    public JLabel getjQuantidade() {
        return jQuantidade;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bCancelar = new javax.swing.JButton();
        bEditar = new javax.swing.JButton();
        jNome = new javax.swing.JLabel();
        jTelefone = new javax.swing.JLabel();
        jQuantidade = new javax.swing.JLabel();
        jDia = new javax.swing.JLabel();
        jEstado = new javax.swing.JLabel();
        tNome = new javax.swing.JTextField();
        tTelefone = new javax.swing.JTextField();
        tQnt = new javax.swing.JTextField();
        tDia = new javax.swing.JFormattedTextField();
        tEstado = new javax.swing.JComboBox();
        jOS = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bCancelar.setText("Cancelar");
        bCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bCancelarMouseClicked(evt);
            }
        });

        bEditar.setText("Editar");
        bEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bEditarMouseClicked(evt);
            }
        });

        jNome.setText("nome");

        jTelefone.setText("telefone");

        jQuantidade.setText("quantidade");

        jDia.setText("dia");

        jEstado.setText("estado");

        tNome.setToolTipText("Nome");

        tTelefone.setToolTipText("Telefone");

        tQnt.setToolTipText("Quantidade");

        try {
            tDia.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/#### ##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tDia.setToolTipText("Data e Hora");
        tDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tDiaActionPerformed(evt);
            }
        });

        tEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PENDENTE", "EMITIDO", "ENTREGUE" }));
        tEstado.setToolTipText("Estado");

        jOS.setText("OS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bCancelar)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(tQnt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDia)
                            .addComponent(tDia, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jEstado)
                                .addGap(30, 30, 30))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tNome, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jNome)
                                .addGap(39, 39, 39)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTelefone)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jOS)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNome)
                    .addComponent(jTelefone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jQuantidade)
                    .addComponent(jDia)
                    .addComponent(jEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tQnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCancelar)
                    .addComponent(bEditar))
                .addGap(3, 3, 3)
                .addComponent(jOS)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCancelarMouseClicked
        this.setVisible(false);
        Editar e = new Editar();
        e.setVisible(true);
    }//GEN-LAST:event_bCancelarMouseClicked

    private void bEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bEditarMouseClicked
        String nome = tNome.getText();
        String telefone = tTelefone.getText();
        String qnt = tQnt.getText();
        String dia = tDia.getText();
        String es = (String) tEstado.getModel().getSelectedItem();
        if (nome.isEmpty() && telefone.isEmpty() && qnt.isEmpty() && (dia.equalsIgnoreCase(jDia.getText()) || dia.equalsIgnoreCase("  /  /       :  ")) && es.equalsIgnoreCase(jEstado.getText())) {
            JOptionPane.showMessageDialog(null, "Você deve informar qual campo deve ser alterado", "Campos em brancos", 2);
            return;
        }
        Excel.getDados().editar(jOS.getText(), nome, telefone, qnt, dia.equalsIgnoreCase("  /  /       :  ") ? jDia.getText().replace(" às", "") : dia, es);
        JOptionPane.showMessageDialog(null, "Editado com sucesso", "Edição completa", 1);
        this.setVisible(false);
        Editar e = new Editar();
        e.setVisible(true);
    }//GEN-LAST:event_bEditarMouseClicked

    private void tDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tDiaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bEditar;
    private javax.swing.JLabel jDia;
    private javax.swing.JLabel jEstado;
    private javax.swing.JLabel jNome;
    private javax.swing.JLabel jOS;
    private javax.swing.JLabel jQuantidade;
    private javax.swing.JLabel jTelefone;
    private javax.swing.JFormattedTextField tDia;
    private javax.swing.JComboBox tEstado;
    private javax.swing.JTextField tNome;
    private javax.swing.JTextField tQnt;
    private javax.swing.JTextField tTelefone;
    // End of variables declaration//GEN-END:variables
}
