/*
 * Projeto destribuido por DEVKEWI COMPANY - Todos os direitos reservados.
 * Para alteração do código fonte estará disposto a concordar com termos.
 */
package me.kewi.interfaces;

import javax.swing.JOptionPane;
import javax.swing.JTextField;
import me.kewi.Excel;

/**
 *
 * @author DEVKEWI COMPANY - Kewilleen
 */
public class Requisitos extends javax.swing.JFrame {

    /**
     * Creates new form Requisitos
     */
    public Requisitos() {
        initComponents();
        setTitle("Requisitar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lCliente = new javax.swing.JLabel();
        tCliente = new javax.swing.JTextField();
        lQuantidade = new javax.swing.JLabel();
        tQuantidade = new javax.swing.JTextField();
        lEntregar = new javax.swing.JLabel();
        tData = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        lTelefone = new javax.swing.JLabel();
        tHora = new javax.swing.JFormattedTextField();
        bSolicitar = new javax.swing.JButton();
        tTelefone = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        bVoltar = new javax.swing.JMenu();
        bLista = new javax.swing.JMenu();
        bEditar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lCliente.setText("Cliente:");

        tCliente.setToolTipText("Nome do cliente");

        lQuantidade.setText("Quantidade:");

        tQuantidade.setToolTipText("Quantidade");

        lEntregar.setText("Entregar dia:");

        try {
            tData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tData.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tData.setToolTipText("Dia da entrega");

        jLabel1.setText("às");

        lTelefone.setText("Telefone");

        try {
            tHora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tHora.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tHora.setToolTipText("Hora da entrega");

        bSolicitar.setText("SOLICITAR");
        bSolicitar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSolicitarMouseClicked(evt);
            }
        });

        tTelefone.setToolTipText("Telefone");

        bVoltar.setText("VOLTAR");
        bVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bVoltarMouseClicked(evt);
            }
        });
        jMenuBar1.add(bVoltar);

        bLista.setText("EXISTENTES");
        bLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bListaMouseClicked(evt);
            }
        });
        jMenuBar1.add(bLista);

        bEditar.setText("EDITAR");
        bEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bEditarMouseClicked(evt);
            }
        });
        jMenuBar1.add(bEditar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lCliente)
                            .addComponent(lTelefone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(tTelefone))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lEntregar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lQuantidade)
                                .addGap(13, 13, 13)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tQuantidade, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(tData))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tHora, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bSolicitar))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCliente)
                    .addComponent(tCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lEntregar)
                    .addComponent(tData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(tHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lQuantidade)
                    .addComponent(tQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lTelefone)
                    .addComponent(tTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bSolicitar)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bVoltarMouseClicked
        this.setVisible(false);
        Representante r = new Representante();
        r.setVisible(true);
    }//GEN-LAST:event_bVoltarMouseClicked

    private void bListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bListaMouseClicked
        this.setVisible(false);
        Existentes e = new Existentes();
        e.setVisible(true);
    }//GEN-LAST:event_bListaMouseClicked

    private void bSolicitarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSolicitarMouseClicked
        Object[] obj = {tCliente, tTelefone, tQuantidade};
        for (Object obj2 : obj) {
            JTextField obj1 = (JTextField) obj2;
            if (obj1.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "O campo \"" + obj1.getToolTipText() + "\" não pode estar em branco", "Campos em brancos", 2);
                return;
            }
        }
        String cliente = tCliente.getText();
        String qnt = tQuantidade.getText();
        String data = tData.getText() + " às " + tHora.getText();
        int result = JOptionPane.showConfirmDialog(null, "Requisitar para o cliente \"" + cliente + "\" " + qnt + " pudim(s) para o dia " + data + "?", "Confirmar", 0);
        if (result == JOptionPane.YES_OPTION) {
            Excel.getDados().inserir(1, tCliente.getText(), tTelefone.getText(), tQuantidade.getText(), tData.getText() + " " + tHora.getText());
            JOptionPane.showMessageDialog(null, "Requisição completa");
            for (Object obj2 : obj) {
                JTextField obj1 = (JTextField) obj2;
                obj1.setText(null);
            }
        }
    }//GEN-LAST:event_bSolicitarMouseClicked

    private void bEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bEditarMouseClicked
        this.setVisible(false);
        Editar e = new Editar();
        e.setVisible(true);
    }//GEN-LAST:event_bEditarMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu bEditar;
    private javax.swing.JMenu bLista;
    private javax.swing.JButton bSolicitar;
    private javax.swing.JMenu bVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lCliente;
    private javax.swing.JLabel lEntregar;
    private javax.swing.JLabel lQuantidade;
    private javax.swing.JLabel lTelefone;
    private javax.swing.JTextField tCliente;
    private javax.swing.JFormattedTextField tData;
    private javax.swing.JFormattedTextField tHora;
    private javax.swing.JTextField tQuantidade;
    private javax.swing.JTextField tTelefone;
    // End of variables declaration//GEN-END:variables
}
