/*
 * Projeto destribuido por DEVKEWI COMPANY - Todos os direitos reservados.
 * Para alteração do código fonte estará disposto a concordar com termos.
 */
package frigobar.display.validade;

import frigobar.display.Menu;
import frigobar.manager.FileManager;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import me.kewi.Frigobar;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;

/**
 *
 * @author DEVKEWI COMPANY - Kewilleen
 */
public class Remover extends javax.swing.JFrame {

    private frigobar.manager.Validation v = Frigobar.getValidation();
    private Menu m = v.getMenu();
    private FileManager fm = v.getFileManager();

    /**
     * Creates new form Remover
     */
    public Remover() {
        initComponents();
        Frigobar.getValidation().minimizar(this);
        setTitle("Verificação de protudos");
        setLocationRelativeTo(null);
        Image img = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/frigobar/imagens/Icon/logo16x16.png"));
        setIconImage(img);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lInfo = new javax.swing.JLabel();
        tId = new javax.swing.JTextField();
        bPesquisar = new javax.swing.JButton();
        bMenuBar = new javax.swing.JMenuBar();
        bMenu = new javax.swing.JMenu();
        bVoltar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lInfo.setText("Digite o ID que deseja remover da demanda");

        tId.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        bPesquisar.setText("Remover");
        bPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bPesquisarMouseClicked(evt);
            }
        });

        bMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frigobar/imagens/Icon/home16x16.png"))); // NOI18N
        bMenu.setText("Menu");
        bMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bMenuMouseClicked(evt);
            }
        });
        bMenuBar.add(bMenu);

        bVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frigobar/imagens/Icon/back16x16.png"))); // NOI18N
        bVoltar.setText("Voltar");
        bVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bVoltarMouseClicked(evt);
            }
        });
        bMenuBar.add(bVoltar);

        setJMenuBar(bMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(tId, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bPesquisar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bPesquisar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMenuMouseClicked
        this.setVisible(false);
        m.setVisible(true);
    }//GEN-LAST:event_bMenuMouseClicked

    private void bVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bVoltarMouseClicked
        Validation display = this.v.getValidation();
        this.setVisible(false);
        display.setVisible(true);
    }//GEN-LAST:event_bVoltarMouseClicked

    private void bPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPesquisarMouseClicked
        String indice = tId.getText();
        if (!Frigobar.isNumeric(indice)) {
            Frigobar.sendInfo(2, "O ID deve ser númerico", "ID irregular");
            return;
        }
        double id = Double.parseDouble(indice);
        if (!v.getValidade().hasProduto(id)) {
            Frigobar.sendInfo(2, "ID não encontrado", "ID inexistente");
            return;
        }
        String produto = v.getValidade().getProduto(id);
        String validade = v.getValidade().getValidade(id);
        int lote = v.getValidade().getLote(id);
        int i = JOptionPane.showConfirmDialog(null, "<html>Deseja remover o ID: " + ((int) id) + "<br>Produto: " + produto + "<br>Validade: " + validade + "<br>Lote: " + lote + "</html>", "Confirmar remoção", JOptionPane.YES_NO_OPTION);
        if (i == 0) {
            v.getValidade().remove(id);
            JTable t = v.getValidation().getTable();
            TableModel tm = t.getModel();
            DefaultTableModel dtm = (DefaultTableModel) tm;
            int rows = dtm.getRowCount();
            System.out.println("Rows: " + rows);
            int idToRemove = 0;
            for (int row = 0; row < rows; row++) {
                System.out.println("Row: " + row);
                int idTable = (int) dtm.getValueAt(row, 0);
                if (idTable == (int) id) {
                    break;
                }
                idToRemove++;
            }
            System.out.println("ID para remoção: " + idToRemove);
            System.out.println("ID próprio: " + id);
            dtm.removeRow(idToRemove);
            try {
                FileInputStream fis = new FileInputStream(fm.getData());
                Workbook w = new HSSFWorkbook(fis);
                Sheet s = w.getSheetAt(0);
                Row r = s.getRow((int) id);
                r.getCell(6).setCellValue("REMOVIDO");
                FileOutputStream fos = new FileOutputStream(fm.getData());
                w.write(fos);
                fos.close();
                w.close();
            } catch (IOException ex) {
                Frigobar.sendInfo(0, ex.getMessage(), "Erro");
            }
            tId.setText("");
            Frigobar.sendInfo(5, "ID \"" + (int) id + "\" tendo produto como \"" + produto + "\"removido", "Removido");
        }
    }//GEN-LAST:event_bPesquisarMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu bMenu;
    private javax.swing.JMenuBar bMenuBar;
    private javax.swing.JButton bPesquisar;
    private javax.swing.JMenu bVoltar;
    private javax.swing.JLabel lInfo;
    private javax.swing.JTextField tId;
    // End of variables declaration//GEN-END:variables
}
