/*
 * Projeto destribuido por DEVKEWI COMPANY - Todos os direitos reservados.
 * Para alteração do código fonte estará disposto a concordar com termos.
 */
package frigobar.display.cadastro;

import frigobar.display.Menu;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import me.kewi.Frigobar;

/**
 *
 * @author DEVKEWI COMPANY - Kewilleen
 */
public class Cadastrar extends javax.swing.JFrame {

    private frigobar.manager.Validation v = Frigobar.getValidation();
    private Menu m = v.getMenu();

    /**
     * Creates new form Cadastrar
     */
    public Cadastrar() {
        initComponents();
        setTitle("Cadastrar Produto");
        setLocationRelativeTo(null);
        Image img = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/frigobar/imagens/Icon/logo16x16.png"));
        setIconImage(img);
        Frigobar.getValidation().minimizar(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tNome = new javax.swing.JTextField();
        lNome = new javax.swing.JLabel();
        tAlmox = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        bInserir = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lNome.setText("Produto:");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cód. Almoxerifado:");

        bInserir.setText("Inserir");
        bInserir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bInserirMouseClicked(evt);
            }
        });

        bCancelar.setText("Cancelar");
        bCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bCancelarMouseClicked(evt);
            }
        });

        jMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frigobar/imagens/Icon/home16x16.png"))); // NOI18N
        jMenu.setText("Menu");
        jMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuMouseClicked(evt);
            }
        });
        jMenuBar.add(jMenu);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bInserir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tNome)
                            .addComponent(lNome, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tAlmox)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNome)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tAlmox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bInserir)
                    .addComponent(bCancelar))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuMouseClicked
        this.setVisible(false);
        m.setVisible(true);
    }//GEN-LAST:event_jMenuMouseClicked

    private void bCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCancelarMouseClicked
        this.setVisible(false);
        m.setVisible(true);
    }//GEN-LAST:event_bCancelarMouseClicked

    private void bInserirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bInserirMouseClicked
        String nome = tNome.getText();
        String almox = tAlmox.getText();
        if (nome.isEmpty() || almox.isEmpty()) {
            String s = nome.isEmpty() ? "Nome do Produto" : almox.isEmpty() ? "Código do Almoxerifado" : "";
            Frigobar.sendInfo(2, "Você deve informar o " + s + " a ser adicionado", "Campo \"" + s + "\" vazio");
            return;
        }
        if (v.getProduto().hasAlmox(almox)) {
            Frigobar.sendInfo(2, "Código do Almoxerifado \"" + almox + "\" tendo nome de \"" + v.getProduto().getProdutoNomePorAlmox(almox) + "\" já está cadastrado", "Produto já cadastrado");
            return;
        }
        if(v.getProduto().hasProduto(nome)){
            Frigobar.sendInfo(2, "Produto \"" + nome + "\" já está cadastrado", "Produto já cadastrado");
            return;
        }
        int i = JOptionPane.showConfirmDialog(null, "Você deseja realmente adicionar o produto \"" + nome + "\" ?", "Confirmar cadastramento", 0, 1);
        if (i == 0) {
            v.setProduto(nome, almox);
            tNome.setText("");
            tAlmox.setText("");
            Frigobar.sendInfo(5, "Produto \"" + nome + "\" cadastrado", "Cadastro realizado");
        }
    }//GEN-LAST:event_bInserirMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bInserir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JLabel lNome;
    private javax.swing.JTextField tAlmox;
    private javax.swing.JTextField tNome;
    // End of variables declaration//GEN-END:variables
}
