/*
 * Projeto destribuido por DEVKEWI COMPANY - Todos os direitos reservados.
 * Para alteração do código fonte estará disposto a concordar com termos.
 */
package frigobar.display.cadastro;

import frigobar.display.Menu;
import java.awt.Image;
import java.awt.Toolkit;
import me.kewi.Frigobar;

/**
 *
 * @author DEVKEWI COMPANY - Kewilleen
 */
public class Validar extends javax.swing.JFrame {

    private frigobar.manager.Validation v = Frigobar.getValidation();
    private Menu m = v.getMenu();
    private String produto, almox;
    private double id;

    public Validar(double id, String nome, String almox) {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Editar cadastrado");
        Image img = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/frigobar/imagens/Icon/logo16x16.png"));
        setIconImage(img);
        Frigobar.getValidation().minimizar(this);
        lProduto.setText(nome);
        lAlmox.setText(almox);
        tProduto.setText(nome);
        tAlmox.setText(almox);
        this.produto = nome;
        this.almox = almox;
        this.id = id;
        System.out.println(id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lProduto = new javax.swing.JLabel();
        lAlmox = new javax.swing.JLabel();
        bEditar = new javax.swing.JButton();
        bVoltar = new javax.swing.JButton();
        tProduto = new javax.swing.JTextField();
        tAlmox = new javax.swing.JTextField();
        lAntigoProduto = new javax.swing.JLabel();
        lAntigoAlmox = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lProduto.setText("Produto");

        lAlmox.setText("Almox");

        bEditar.setText("Editar");
        bEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bEditarMouseClicked(evt);
            }
        });

        bVoltar.setText("Voltar");
        bVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bVoltarMouseClicked(evt);
            }
        });

        lAntigoProduto.setText("Produto:");

        lAntigoAlmox.setText("Cód.Almox.:");

        jMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frigobar/imagens/Icon/home16x16.png"))); // NOI18N
        jMenu.setText("Menu");
        jMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuMouseClicked(evt);
            }
        });
        jMenuBar.add(jMenu);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lAntigoProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tAlmox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lAntigoAlmox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lAlmox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(bVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bEditar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lProduto)
                    .addComponent(lAlmox)
                    .addComponent(lAntigoProduto)
                    .addComponent(lAntigoAlmox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tAlmox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bEditar)
                    .addComponent(bVoltar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuMouseClicked
        this.setVisible(false);
        m.setVisible(true);
    }//GEN-LAST:event_jMenuMouseClicked

    private void bVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bVoltarMouseClicked
        this.setVisible(false);
        Editar e = new Editar();
        e.setVisible(true);
    }//GEN-LAST:event_bVoltarMouseClicked

    private void bEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bEditarMouseClicked
        String novoProduto = tProduto.getText();
        String novoAlmox = tAlmox.getText();
        if (novoProduto.equalsIgnoreCase(produto) && novoAlmox.equalsIgnoreCase(almox)) {
            Frigobar.sendInfo(2, "Não houve alteração no nome do produto quanto no código do almoxerifado", "Sem alteração");
            return;
        }
        if (novoProduto.equalsIgnoreCase(produto)) {
            v.editarAlmox(id, novoAlmox);
            Frigobar.sendInfo(5, "O código do almoxerifado \"" + almox + "\" foi alterado para \"" + novoAlmox + "\"", "Alterado com sucesso");
            this.setVisible(false);
            Editar e = new Editar();
            e.setVisible(true);
            return;
        }
        if (novoAlmox.equalsIgnoreCase(almox)) {
            v.editarProduto(id, novoProduto);
            Frigobar.sendInfo(5, "O nome do produto \"" + produto + "\" foi alterado para \"" + novoProduto + "\"", "Alterado com sucesso");
            this.setVisible(false);
            Editar e = new Editar();
            e.setVisible(true);
        }
    }//GEN-LAST:event_bEditarMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEditar;
    private javax.swing.JButton bVoltar;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JLabel lAlmox;
    private javax.swing.JLabel lAntigoAlmox;
    private javax.swing.JLabel lAntigoProduto;
    private javax.swing.JLabel lProduto;
    private javax.swing.JTextField tAlmox;
    private javax.swing.JTextField tProduto;
    // End of variables declaration//GEN-END:variables
}
